trigger:
- master

stages:
  - stage: Build
    pool:
      name: Local
      demands:
        - agent.name -equals VM1    
      vmImage: 'windows-latest'
    jobs:
    - job: Build
      displayName: 'Powershell Script Execute'
      steps:
        - task: PublishBuildArtifacts
          inputs:
            PathtoPublish: 'C:'
            ArtifactName: 'allprojnameid.csv'
